### ISSUE TITLE
unable to compile with org 0000h

### ISSUE THREAD

**Issue by xerxex351** [floooh/vscode-kcide#7]
I'm working in my z80 kernel and I can compile and run my software when org is > 0. 

I got an error when org is 0. I think it should be linked to curAddr in file **assembler.ts** that it returns error when curAddr = 0

I suppose it should be linked to line 191. 
     if (curSymbol && curAddr) {

**Comment by floooh** [comment]
Yeah good catch. I think that if() needs to check that curAddr isn't NaN instead. I'll try to fix this in the couple of days.

**Comment by floooh** [comment]
Ok, this should be fixed in version 1.8.2 (currently verifying but should show up in a couple of minutes).

Thanks for the bug report!

**Comment by xerxex351** [comment]
Thanks! it is fixed
